version: "3"
services:
  magento:
    image: "malexcheng/magento2"
    ports:
      - "${MAGENTO_HTTP_PORT}:80"
    volumes:
      - "${APP_CODE_PATH_HOST}:/var/www/html/app/design/frontend/mytheme/default"
  mysql:
    build:
      context: "mysql"
      args:
        - "MYSQL_VERSION=${MYSQL_VERSION}"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "TZ=${WORKSPACE_TIMEZONE}"
    volumes:
      - "${DATA_PATH_HOST}/mysql:/var/lib/mysql"
      - "${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d"
    ports:
      - "${MYSQL_PORT}:3306"
volumes:
  mysql:
    driver: "${VOLUMES_DRIVER}"
